name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clean Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: SSH Login and deploy
        run: |
          echo "deploying..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /$USER/repos/paladins_wheelspin/ && git pull && rm -rf node_modules package-lock.json && npm install && npm run build"
          echo "deployed"

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
